### ISSUE TITLE
Doesn't run on NixOS 16.03

### ISSUE THREAD

**Issue by magnetophon** [tsoding/midi-looper#101]
Thanks for making this!

Unfortunately I wasn't able to get it to run using your commands:

```
 Compiling dimooper v0.1.0 (file:///home/bart/source/dimooper)
src/measure.rs:59:5: 61:6 warning: method is never used: `tempo_bpm`, #[warn(dead_code)] on by default
src/measure.rs:59     pub fn tempo_bpm(&self) -> u32 {
                      ^
src/measure.rs:67:5: 69:6 warning: method is never used: `quantation_level`, #[warn(dead_code)] on by default
src/measure.rs:67     pub fn quantation_level(&self) -> u32 {
                      ^
src/measure.rs:76:5: 79:6 warning: method is never used: `update_measure_size_bpm`, #[warn(dead_code)] on by default
src/measure.rs:76     pub fn update_measure_size_bpm(&mut self, measure_size_bpm: u32) {
                      ^
src/measure.rs:81:5: 84:6 warning: method is never used: `update_quantation_level`, #[warn(dead_code)] on by default
src/measure.rs:81     pub fn update_quantation_level(&mut self, quantation_level: u32) {
                      ^
     Running `target/debug/dimooper`
0) Output: Midi Through Port-0
1) Input: Midi Through Port-0
2) Output: qjackctl
Usage: ./dimooper <input-port> <output-port>
error: Process didn't exit successfully: `target/debug/dimooper` (exit code: 1)
```

I also tried: `target/debug/dimooper 2 2` and got:

```
Listening on: 2 qjackctl
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotAnInputDevice', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Hope that helps!

**Comment by rexim** [comment]
Oh, my! Looks like the instructions are incomplete! I've never expected someone to actually use this except myself. :) Let me make more detailed and better instructions. I will provide the link here when I'm done. Basically, dimooper requires an external synthesizer. QSynth is fine. You need to have QSynth and dimooper running simultaneously. Then do `cargo run <midi-controler-input-port> <synthesizer-output-port>`. I'll provide more details in the instructions.

Also, a little WARNING. Dimooper is currently at really unstable development phase. It's not a finished program and something may work incorrectly or unexpectedly. I won't be surprised if it works only on my setup with Novation Launchkey Mini :D So, please be careful using that thing.

**Comment by rexim** [comment]
And thank you very much for reporting this! :)

**Comment by rexim** [comment]
I'll try to find some time to prepare the setup guide tomorrow.

**Comment by magnetophon** [comment]
@rexim Great! Looking forward to doing that stadium gig I have tomorrow, using this mature and well tested piece of software!  ;)

(just to be clear: I'm not making fun of your software!  Just thought it was funny how you told me to be careful.  :smile:  )

**Comment by rexim** [comment]
@magnetophon I described my setup as close as I could in a form of a guide here: https://github.com/tsoding/dimooper/wiki/NixOS-QSynth-Setup-Guide

Could you please take a look when you get a chance and provide your comments on that? Did this information help you to make Dimooper running?

Thanks!

**Comment by magnetophon** [comment]
Thanks.
Which problems are you having with jack?
Maybe I can help.

Wow!!! sounds impressive:  : 

```
warning: working around a Linux kernel bug by creating a hole of 2093056 bytes in ‘/nix/store/qkbha3y71xz95jvkj980989mbb72pk9q-rust-nightly-2016-06-12/bin/rustc’
warning: working around a Linux kernel bug by creating a hole of 2093056 bytes in ‘/nix/store/qkbha3y71xz95jvkj980989mbb72pk9q-rust-nightly-2016-06-12/bin/rustdoc’
warning: working around a Linux kernel bug by creating a hole of 569344 bytes in ‘/nix/store/qkbha3y71xz95jvkj980989mbb72pk9q-rust-nightly-2016-06-12/bin/cargo’
```

**Comment by magnetophon** [comment]
I runs!  I haven't tried with sound yet, as my PC is in a massive compile, plus I don't have a midi-source handy, but I'm sure it'll be fine. Will reopen otherwise.

Thanks!

**Comment by rexim** [comment]
> Thanks.
> Which problems are you having with jack?
> Maybe I can help.

Oh, that would be great! Thanks! :) It was a while ago, so I even forgot what was the problem. :D Let me try to reproduce it again and describe everything in details. Unfortunately, it's 3am on my side and right now I'd like to go to sleep. So, please expect some delay with that. :)

> I runs! I haven't tried with sound yet, as my PC is in a massive compile, plus I don't have a midi-source handy, but I'm sure it'll be fine. Will reopen otherwise.

Woah! I'm so glad! :) I'm not sure how you found this project, but I stream the development process of it. If you are interested to see Dimooper in action you may want to take a look at this https://twitter.com/tsoding/status/742798596576321536

Have fun!

**Comment by rexim** [comment]
And something from the last stream with the latest version https://www.youtube.com/watch?v=v6QzKTvwTJE&t=6827
