### ISSUE TITLE
Segfaults on CI

### ISSUE THREAD

**Issue by rexim** [tsoding/midi-looper#121]
It starts to happen quite often. We need to investigate that
- https://travis-ci.org/tsoding/dimooper/builds/155026791
- https://travis-ci.org/tsoding/dimooper/builds/151591516
- https://travis-ci.org/tsoding/dimooper/builds/151576651
- https://travis-ci.org/tsoding/dimooper/builds/151564221

**Comment by rexim** [comment]
Also, I've never experienced that locally.

**Comment by basilevs** [comment]
From mtlcker:

> Try nightly Rust on Travis.https://docs.travis-ci.com/user/languages/rust
>  I think you introduced a dependency that fails on stable, but works on nightly Rust version.

**Comment by rexim** [comment]
These are the tests that passed on CI:

```
test looper::sample::tests::test_amount_of_measure_calculation ... ok
test looper::sample::tests::test_get_next_messages ... ok
test measure::tests::test_measure_new ... ok
test measure::tests::test_measure_update ... ok
test measure::tests::test_quants_per_measure ... ok
test measure::tests::test_scale_time_cursor ... ok
test measure::tests::test_timestamp_quant_conversion ... ok
```

This is entire set of tests:

```
test looper::sample::tests::test_amount_of_measure_calculation ... ok
test looper::sample::tests::test_get_next_messages ... ok
test measure::tests::test_measure_new ... ok
test measure::tests::test_measure_update ... ok
test measure::tests::test_quants_per_measure ... ok
test measure::tests::test_scale_time_cursor ... ok
test measure::tests::test_timestamp_quant_conversion ... ok
test popup::tests::test_bump_alpha ... ok
test popup::tests::test_make_texture_rect ... ok
test tests::test_hello ... ok
```

Looks like popup tests cause the segfault. It probably happens because I initialize ttf_context without initializing sdl2 context. https://github.com/tsoding/dimooper/blob/6ccfe97beb521cc19e911d8b5ede910006aefd28/src/popup.rs#L95
