### ISSUE TITLE
End started notes on exit

### ISSUE THREAD

**Issue by basilevs** [tsoding/midi-looper#42]
### Description

Now synthesizer often has to be reset after terminating looper from looping state. This would be nice to automate.

**Comment by rexim** [comment]
Thanks! Accepted!

**Comment by basilevs** [comment]
I'm not sure how open notes are handled on transitions from recording to looping, and on every loop iteration during replay, but may be they should be closed then too.

**Comment by rexim** [comment]
Yeah, true. Looks like a separate but still related issue. I'm gonna file it when I feel right. :)
